# Mongo Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cust-mongo-soar
  labels:
    run: cust-mongo-soar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: cust-mongo-soar
    spec:
      containers:
      - image: mongo:3.2.9
        name: cust-mongo-soar
        ports:
        - name: cust-mongo-soar
          containerPort: 27020
          hostPort: 27020
      restartPolicy: Always

---

# Mongo Service
apiVersion: v1
kind: Service
metadata:
  name: cust-mongo-soar
  labels:
    run: cust-mongo-soar
spec:
  clusterIP: None
  ports:
  - port: 27020
    targetPort: 27020
  selector:
    run: cust-mongo-soar
