# APP DEPLOYMENT
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer-ms
  name: customer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_HOST
          value: cust-mongo-soar
        - name: MONGO_PORT
          value: "27020"
        - name: KAFKA_BROKER
          value: "18.184.145.38:9092"
        - name: KAFKA_REGISTRY
          value: "http://18.184.145.38:18081"
        image: lonneke/customer-ms:1.0.2
        name: customer-ms
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-ms
  name: customer-ms
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer-ms
  type: LoadBalancer