version: '2'
services:
  customer-ms:
      #Image
      image: lonneke/customer-ms:2.0
      build: ./src/node/CustomerApplication
      environment:
        PORT: 8080
        MONGO_HOST: 'cust-mongo-db'
        KAFKA_BROKER: '129.156.113.171:6667'
        KAFKA_REGISTRY: 'http://129.156.113.125:8081'
      ports:
        - "8080:8080"
      command: npm start
      links:
        - cust-mongo-db

  cust-mongo-db:
      image: mongo:3.2.9
