version: '2'
services:
  customer-ms:
      #Image
      image: lonneke/customer-ms:2.0.1
      build: ./src/node/CustomerApplication
      environment:
        LOG_LEVEL: 'debug'
        PORT: 8080
        MONGO_HOST: 'cust-mongo-db'
        KAFKA_BROKER: '129.156.113.171:6667'      
        KAFKA_REGISTRY: 'http://129.156.113.125:8081'
        PUBLISH: 'true'
        KAFKA_SIGNIN_TOPIC: 'idcs-1d61df536acb4e9d929e79a92f3414b5-soaringusersignins'
        KAFA_CUSTOMER_TOPIC: 'idcs-1d61df536acb4e9d929e79a92f3414b5-soaringcustomers'
      ports:
        - "8080:8080"
      command: npm start
      links:
        - cust-mongo-db

  cust-mongo-db:
      image: mongo:3.2.9
